FROM node:lts-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

ENV NODE_ENV=development

EXPOSE 9090

# Use pnpm to run the development script
CMD ["pnpm", "run", "dev"]
